### PR TITLE
Update IP Geolocation Service

### LINKED ISSUE #31: Found a solution to auto location not working
For those that are having problems with the auto location, it's due to freegeoip.net being down. As far as I can tell it's been down for a while.

I've found an alternative free IP geolocation service(http://ip-api.com) and it's very easy to modify the current `get-weather` code to use it.

At https://github.com/felixhageloh/weather-widget/blob/master/weather.widget/get-weather#L31, change:

```
var request = getJSON("http://freegeoip.net/json/", callback);
```

to

```
var request = getJSON("http://ip-api.com/json", callback);
```

The API returns a `region` attribute instead of `region_name`, so change https://github.com/felixhageloh/weather-widget/blob/master/weather.widget/get-weather#L20

```
options.region = location.region_name;
```
to
```
options.region = location.region;
```

If this is something you want in this repo I can make a PR.

### PR DESCRIPTION
**Pull request by aaronvb**
- Remove freegeoip.net
- Add ip-api.com
- Change callback region param to work with ip-api

Fixes #31

### CODE REVIEW

**Comment by felixhageloh** [comment]
great thanks! Can you also update the widget zip file, so I can just merge this in?

**Comment by aaronvb** [comment]
Sure thing, I'll make those changes in a few!

**Comment by aaronvb** [comment]
- Updated README
- Updated zip file

**Comment by felixhageloh** [comment]
awesome, merged! Thanks again

**Pull request merged**
