### PR TITLE
Putting back icons.svg, adding optional requests library

### PR DESCRIPTION
**Pull request by nickroberts**
Sorry about those icons!

I put back the icons.svg file, along with adding an option to use the python `requests` library.

Very weird how I was getting an `HTTP version not supported` error while at the local coffeeshop.

Also updated the README, explaining how to use the `requests` library.

Thanks!

### CODE REVIEW

**Comment by finfio** [comment]
I'm trying to customize your widget for my own location Padov (Padua) in Italy...
I'm trying to set region to "PD" or "IT" or Italy etc, but it gives me token ILLEGAL.
Should I make any correction to the code?
Thank you in advance,
Fiorenzo
Italy

**Comment by martinorob** [comment]
City = Padova
Region = Italy

;)

Martino

--
Inviato da iPhone

**Comment by finfio** [comment]
Sorry.
The problem was my text editor substituting '' with "
Now it works!

Il lunedì 9 febbraio 2015, martinorob <notifications@github.com> ha scritto:

> City = Padova
> Region = Italy
>
> ;)
>
> Martino
>
> --
> Inviato da iPhone
>
> > Il giorno 09/feb/2015, alle ore 13:11, finfio <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:
> >
> > I'm trying to customize your widget for my own location Padov (Padua) in
> Italy...
> > I'm trying to set region to "PD" or "IT" or Italy etc, but it gives me
> token ILLEGAL.
> > Should I make any correction to the code?
> > Thank you in advance,
> > Fiorenzo
> > Italy
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixhageloh/weather-widget/pull/6#issuecomment-73500864>
> .
>


-- 
Fiorenzo Fina
Mobile: +39-334-5645440
Email: finfio@gmail.com
Address: via Fowst, 10/B - 35135 Padova - Italy
<http://it.linkedin.com/in/fiorenzofina/>

**Comment by felixhageloh** [comment]
no worries, great you figured it out!

**Pull request closed without merging**
