### PR TITLE
New parameters - easy resizing, and more show/hide options

### PR DESCRIPTION
**Pull request by jmcguire**
In sum: You can easily resize the entire widget with a single parameter. Plus a few more show/hide options.

 - **baseFontSize** - Resize the entire widget with this parameter. All
   sizes are driven from this number, which defaults to 42.

 - **showLocation** - Change how this works from "display:none" to
   "visibility:hidden". This because if this and showDay are both false
   the span.temperature with drop down, ruining the nice look-n-feel.

 - **showDay** - Show (or hide) the current day of the week. This
   doesn't affect the forecast.

 - **showWeatherText** - Show (or hide) the weather text.

 - **showForecast** - Show (or hide) the entire forecast widget. We have
   to manually undo the border property.

### CODE REVIEW

**Comment by felixhageloh** [comment]
Sounds good! I didn't get a chance to look at it this weekend but I will see if I can check it (and merge it) later today

**Comment by felixhageloh** [comment]
Thanks for the improvements - they look good from what I can tell! 
The thing is, I don't have much time to maintain this widget at the moment. If you are ok to fix potential bugs resulting from this PR I can merge it tho.

**Comment by jmcguire** [comment]
I can do that.

**Comment by felixhageloh** [comment]
awesome, merging in!

**Pull request merged**
