### PR TITLE
Issue #36

### PR DESCRIPTION
**Pull request by kyletitus**
https://github.com/felixhageloh/weather-widget/issues/36

Added in simple retry logic to the get-weather.js file, this has a hardcoded max of 5 tries.
Added in simple caching via localstorage to the main coffeescript file.

I am mainly a back end guy, js/coffee are not languages I usually work in. Feel free to rip these changes apart. That being said, everything seems to be working on my machine locally.

### CODE REVIEW

**Comment by kevanchristmas** [comment]
Working fine for me so far - thanks for the effort!

**Comment by kyletitus** [comment]
Made a quick update, was getting some stack traces when the widget tried refreshing after opening up my laptop from sleep. Just bad handling.

**Comment by felixhageloh** [comment]
Thanks again for the PR!
Unfortunately I need to discontinue this widget because I have absolutely no time to maintain it. Of course I will leave the code available and I will add any fork of this widget to the widget gallery again. 
Would you by any chance be willing to take over this widget?

**Comment by kyletitus** [comment]
I can take it over and at least keep it working as is. If anything happens that would cause a major overhaul (yahoo api breaking further) I most likely not be able to support it, but would at least give it the old college try.

**Comment by felixhageloh** [comment]
I think in this case I will just merge your PR for now - I don't want to push this on to you -  and then ask around if anyone is interested in adopting this widget

**Pull request merged**
